### ISSUE TITLE
[Driver Request] <Wiser HomeTouch >

### ISSUE THREAD

**Issue by Blaze2be** [Signalare/com.se.wiserapp#15]
**Do you have access to the device you want the app to support?**

**Can you provide basic zigbee info of the device?**
Manufacturer name: Wiser HomeTouch
Product id: MEG5050-0000
Device id: 
Profile id: 

**Link to Schneider Electric product page (english/swedish)**

**Please provide link to deviceInfo() if possible. https://www.se.com/de/de/home/smart-home/wiser/home-touch/)**

**Comment by ablanc13** [comment]
i want too :)

**Comment by ablanc13** [comment]
possible one day the support of the wiser home touch. I can help with information retrieval

**Comment by ablanc13** [comment]
Hello, still nothing planned to integrate the wiser home touc h?

**Comment by Gouss1969** [comment]
Good evening, no interest to develop the Home Touch interface. This device should disappear in the coming month for one new Wiser interface. Sorry if you have got one

**Comment by h3rman** [comment]
Yes. The Home Touch GW is discontinued by SE. No support will be added. Closing issue
