### ISSUE TITLE
Homey 5.0 support - wiser not working

### ISSUE THREAD

**Issue by sOnicen** [Signalare/com.se.wiserapp#18]
Since Homey got update to 5.0 wiser stopped working.

Its possible to add them again but they show up as unknown devices without settings.

**Comment by h3rman** [comment]
Zigbee or Z-Wave? Which models?

**Comment by sOnicen** [comment]
Zigbee / Bluetooth. All models listed as supported devices in v0.1.0 are affected.

**Comment by h3rman** [comment]
Version 0.2.3 should work better. I released it to stable yesterday, can your test it with the new version?

**Comment by sOnicen** [comment]
Worked! Bra jobbat ;)

**Comment by h3rman** [comment]
Great!
