### ISSUE TITLE
No Connection

### ISSUE THREAD

**Issue by mzellmer** [Signalare/com.se.wiserapp#20]
Any idea why my wiser Rotary dimmers no long respond to flows after update Homey 5.0.2?

c5237b6f-da6d-4e35-b24e-55b75c6d37cd

**Comment by h3rman** [comment]
Doesn't seem like a app error, the devices doesn't respond when app is trying to communicate. Investigate zigbee network.

If no response to this issue before 2021-08-01, then I'm closing it.
