### ISSUE TITLE
[Driver Request] <product name>

### ISSUE THREAD

**Issue by ablanc13** [Signalare/com.se.wiserapp#3]
**Do you have access to the device you want the app to support?**
yes

**Can you provide basic zigbee info of the device?**
Manufacturer name: 
Product id: SCHCCT5010-0001, SCHS520567, SCHS520522, SCHS520530
Device id: 
Profile id: 

**Link to Schneider Electric product page (english/swedish)**

**Please provide link to deviceInfo() if possible. [pastebin.com](https://pastebin.com/)**

**Comment by ablanc13** [comment]
Do you have access to the device you want the app to support?
yes

Can you provide basic zigbee info of the device?
Manufacturer name: wiser home touch
Product id: CCT501510
Device id:
Profile id:

I am ready to help you with the integration of the wiser home touch. if you tell me what to do
Link to Schneider Electric product page (english/swedish)

**Comment by h3rman** [comment]
CCT5010-0001 should already work in the app. The other requests are split into new issues. Closing this issue
see #27 #28 #29
