### ISSUE TITLE
Cannot pair with Homey

### ISSUE THREAD

**Issue by ajoj74** [Signalare/com.se.wiserapp#4]
I'm not able to pair my Schneider Wiser rotary switch with Homey. I've also tried to do the reset (3x0.5+10) but it doesn't help. The switch can be paired with my phone in the android app. I've also tried the place homey realy close (<10cm) when trying to pair, but still without success. Any ideas what could be wrong?
Homey version 4.0.0

**Comment by ajoj74** [comment]
Thanks! That solved it. The Wiser manual is not really clear and actually
doesn't mention zigbee at all. It is also strange that according to the
manual 3x0.5+20 should reset it to bluetooth mode. Anyhow, great that it
works now. :)
BTW Do you know if there is any plan to support setting of the min/max dim
level in the Homey app?

Den fre 6 mars 2020 kl 01:04 skrev Johan Bendz <notifications@github.com>:

**Comment by JohanBendz** [comment]
@ajoj74 The 20+ second push is actually altering the device between the two modes.

A wish for a min/max dim setting.. noted.

**Comment by h3rman** [comment]
Min/max dim setting is coming in version 0.1.0. A test version is released and the sharp version will be available in a week or so.
