### ISSUE TITLE
[Driver Request] <wiser gateway>

### ISSUE THREAD

**Issue by ericedberg** [Signalare/com.se.wiserapp#41]
**Do you have access to the device you want the app to support?**
Yes

**Can you provide basic zigbee info of the device?**
Manufacturer name: CCT501901
Product id: 
Device id: 
Profile id: 

**Link to Schneider Electric product page (english/swedish)**

https://www.se.com/se/sv/product/CCT501901/gateway-wiser-används-som-nätverksnod-hanteras-via-wiser-by-seappen-zigbee-3-0-vit/

**Please provide link to deviceInfo() if possible. [pastebin.com](https://pastebin.com/)**

**Comment by h3rman** [comment]
This app is only intended for use without a Wiser gateway. I have no plans at all to add support for this. In addition, it would have been messy for end users to support both direct connection and via gateway in the same app.

Sorry to being bearer of bad news. Closing the issue.
