### ISSUE TITLE
Devices stop responding after Homey reboot

### ISSUE THREAD

**Issue by lovethyresson** [Signalare/com.se.wiserapp#51]
Hey,

I've got a super strange issue. Every time Homey reboots all of my  Zigbee routers (Rotary dimmers and smart plugs), stop processing commands. If I cut mains power (Ie power cycle both homey and the zigbee devices), everything starts working again.

Like this:

1. All Zigbee devices work as normal
2. Homey is rebooted
3. All Zigbee devices stop responding to commands and pass information (from what I can tell)
4. Cut mains power to the house so all Zigbee routers (Schneider Rotary dimmers and smart plugs) reboot
5. Everything works again.

If I were to guess there's something failing with reestablishing the session after a reboot. I've waited 24h and they still haven't come back up.

I was just curious to hear if you've heard anything similar or have any idea what the issue could be?

**Comment by h3rman** [comment]
Is it repeatable? Can you submit a crash report?

**Comment by lovethyresson** [comment]
It is repeatable yes. Submitted a diag now. f47edefe-a639-4d96-97a5-4f132e4fde61

**Comment by h3rman** [comment]
Are your devices marked as unavailable?

[stacktrace.txt](https://github.com/Signalare/com.se.wiserapp/files/9175642/stacktrace.txt)

**Comment by lovethyresson** [comment]
The plugs are, not the rotary dimmers.

**Comment by lovethyresson** [comment]
Would it help if I reboot homey and put it in the weird state and generate a new diagnostic report?

**Comment by h3rman** [comment]
Yes, the last stacktrace didn’t show anything

**Comment by lovethyresson** [comment]
Here's a new one with the error reproduced. This is just after reboot and I've been trying to control a few devices which failed.

77a0f9f7-cf73-4faf-8ee2-b3a48f35afb1

![image](https://user-images.githubusercontent.com/57791059/180717844-ed8683fc-9384-4b89-98b0-43df54d687d5.png)

**Comment by lovethyresson** [comment]
Did the new logs give you anything @h3rman?
