### ISSUE TITLE
cct99100

### ISSUE THREAD

**Issue by Cervik21** [Signalare/com.se.wiserapp#58]
In Homey pro :
Missing support for cct99100

**Comment by h3rman** [comment]
I can’t see that CCT99100 is a zigbee/z-wave device.

https://download.schneider-electric.com/files?p_enDocType=Instruction+sheet&p_File_Name=CCT99100_HW_2015_43_SV.pdf&p_Doc_Ref=CCT99100_IS

**Comment by h3rman** [comment]
This is not a smart home product, closing.
